### PR TITLE
Show curl error when build creation fails

### PR DESCRIPTION
**Pull request by jeremy**
https://github.com/buildkite/trigger-pipeline-action/pull/6#issuecomment-811059151

References #21 #23 #26 #27

### CODE REVIEW

**Comment by ohookins** [comment]
Would love to see this merged.

**Comment by EnricoMi** [comment]
I think in contrast to #26, this fix does not show the Buildkite error message of the JSON response, but only the HTTP message, which might be less verbose. Can be combined with #26 to have both.

**Comment by EnricoMi** [comment]
I have included this in #26.

**Comment by EnricoMi** [comment]
@jeremy this has been merged into master (via #26)
@lizrabuya I think, this issue can be closed as well

**Pull request closed without merging**
