### PR TITLE
SUP-1408 - Remove support of the ENV vars 

### PR DESCRIPTION
**Pull request by lizrabuya**
This PR deprecates the support for setting env vars to send configuration through the GitHub Actions. The trigger-pipeline-action is now configured with an action metadata.

However, there is a difference with the v1.6.0 actions metadata with the proposed v2.0.0 actions. This is to follow the naming convention for configuration variables](https://docs.github.com/en/actions/learn-github-actions/variables#naming-conventions-for-configuration-variables) and not to deviate much on the the naming for the previous ENV vars defined.

## Action metadata name change
Below was the 1.6.0 actions metadata:

```
name: 'Trigger Buildkite Pipeline'
author: 'Buildkite'
description: 'A GitHub Action for triggering a build on a Buildkite pipeline.'
inputs:
   buildkite-token:
     description: 'Buildkite API Access Token'
     required: false
   pipeline:
     description: 'The pipline to create a build on, in the format <org-slug>/<pipeline-slug>'
     required: false
   commit:
     description: 'The commit SHA of the build'
     required: false
   branch:
     description: 'The branch of the build'
     required: false
   message:
     description: 'The message for the build'
     required: false
   build-env-vars:
     description: 'Additional environment variables to set on the build, in JSON format'
     required: false
   build-meta-data:
     description: 'Meta-data to set on the build, in JSON format'
     required: false
   ignore-pipeline-branch-filter:
     description: 'Ignore pipeline branch filtering when creating a new build. true or false'
     required: false
```

This will be the configuration variables in v2.0 onwards:

```
name: 'Trigger Buildkite Pipeline'
author: 'Buildkite'
description: 'A GitHub Action for triggering a build on a Buildkite pipeline.'
inputs:
   buildkite_api_access_token:
     description: 'Buildkite API Access Token'
     required: true
   pipeline:
     description: 'The pipline to create a build on, in the format <org-slug>/<pipeline-slug>'
     required: true
   commit:
     description: 'The commit SHA of the build'
     required: false
     default: HEAD
   branch:
     description: 'The branch of the build'
     required: false
   message:
     description: 'The message for the build'
     required: false
   build_env_vars:
     description: 'Additional environment variables to set on the build, in JSON format'
     required: false
   build_meta_data:
     description: 'Meta-data to set on the build, in JSON format'
     required: false
   ignore_pipeline_branch_filter:
     description: 'Ignore pipeline branch filtering when creating a new build. true or false'
     required: false
```

## Unit and Integration Tests
The addition of unit and integration tests is out of scope for this PR. But initial work has been added to implement some integration tests and unit tests using Github Actions workflow. However, since integration tests require a BUILDKITE API ACCESS TOKEN to be stored as a repo secret variable, running the tests is only advisable to be ran on a fork. 
The unit test is also not fully working, so both test workflows can be added in this PR as reference. Another PR needs to be raised to fix the unit test.  Given these current issues, these workflows will be disabled in the repo. I recommend that Unit and Integration testing using Github Actions can be scoped separately.

### CODE REVIEW

**Review by james2791 — APPROVED** [review]
🚀

**Review by mcncl — APPROVED** [review]
Full steam ahead!

**Review by jradtilbrook — APPROVED** [review]
This looks okay but I dont see any checks on the PR. It looks like the actions haven't run so I don't know if they actually work.

Should they have been run?

**Comment by lizrabuya** [comment]
@jradtilbrook , I have disabled the actions as explained in the PR above. Integration tests has to be run from a fork due to the setting of API access tokens to run the integrations.

**Pull request merged**
